name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - docs
  # Allow the workflow to be triggered also manually.
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mainline
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_PACKAGES: build-base rust musl-dev libffi-dev openssl-dev cargo
