name: Flake8
on: [push, pull_request]

jobs:
  flake:    

    runs-on: ubuntu-latest
    steps:      

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          path: new_branch


      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: awslabs/aws-htc-grid
          path: main-branch
          ref: gh-pages
      
      - name: Install Flake8
        run: |-
          pip3 install flake8
      - run: ls -l -a
      - run: pwd
      
#       - name: run flake8 on the new branch
#         run: flake8 --config ./new_branch/.github/workflows/flake8.config --exit-zero ./new_branch --output-file new.out

#       - name: run flake8 on the new main
#         run: flake8 --config ./new_branch/.github/workflows/flake8.config --exit-zero ./main-branch --output-file main.out
        
      - name: run flake8 on the new branch
        run: cd ./new_branch/ && flake8 --config ./.github/workflows/flake8.config --exit-zero ./ --output-file ./../new.out && cd ./../

      - name: run flake8 on the new main
        run: cd ./main-branch/ && flake8 --config ./../new_branch/.github/workflows/flake8.config --exit-zero ./ --output-file ./../main.out && cd ./../
        
      - name: check
        run: |-
          pwd
          ls -l -a
          cat new.out
          cat main.out
          echo "Differences"
          diff new.out main.out || true
          
      - name: Line Count Check
        run: |-
          echo 'if [ "$(wc -l < new.out )" != "$(wc -l < main.out )" ]; then echo "Warning No Match!"; exit 1; fi; exit 0' >> script.sh
        
        
      - name: Line Count Check2
        run: |-
          wc -l new.out
          wc -l main.out
          cat script.sh
          bash ./script.sh
        
