name: Flake8
on: [push, pull_request]

jobs:
  flake:    

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Checkout HEAD
      - uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Install Flake8
        run: |-
          pip3 install flake8
      - run: ls -l -a
      - run: pwd
      - name: run flake8
        run: flake8 --config ./.github/workflows/flake8.config
