name: Flake8
on: [push, pull_request]

jobs:
  flake:    

    runs-on: ubuntu-latest
    steps:      

      - name: Checkout
        uses: actions/checkout@v3


      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: awslabs/aws-htc-grid
          path: ./../main-branch
      
      - name: Install Flake8
        run: |-
          pip3 install flake8
      - run: ls -l -a
      - run: pwd
      
      - name: run flake8 on the new branch
        run: flake8 --config ./.github/workflows/flake8.config ./

      - name: run flake8 on the new main
        run: flake8 --config ./.github/workflows/flake8.config ./../main-branch
