name: Flake8
on: [push, pull_request]

jobs:
  flake:    

    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: new_branch
      MAIN_BRANCH: main_branch
      NEW_BRANCH_REPORT_FILE: new_branch_report_file
      MAIN_BRANCH_REPORT_FILE: main_branch_report_file
    steps:      

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          path: ${{ env.NEW_BRANCH }}


      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: awslabs/aws-htc-grid
          path: ${{ env.MAIN_BRANCH }}
#           ref: gh-pages
      
      - name: Install Flake8
        run: |-
          pip3 install flake8
      - run: ls -l -a
      - run: pwd
      
     
      - name: run flake8 on the new branch
        run: cd ./${{ env.NEW_BRANCH }}/ && flake8 --config ./.github/workflows/flake8.config --exit-zero ./ --output-file ./../${{ env.NEW_BRANCH_REPORT_FILE }} && cd ./../

      - name: run flake8 on the new main
        run: cd ./${{ env.MAIN_BRANCH }}/ && flake8 --config ./../${{ env.NEW_BRANCH }}/.github/workflows/flake8.config --exit-zero ./ --output-file ./../${{ env.MAIN_BRANCH_REPORT_FILE }} && cd ./../
        
      - name: check
        run: |-
          pwd
          ls -l -a
          cat new.out
          cat main.out
          echo "Differences"
          diff ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }} || true
          
      - name: Line Count Check
        run: |-
          echo 'if [ "$(wc -l < $1 )" -lt "$(wc -l < $2 )" ]; then echo "Warning No Match!"; exit 1; fi; exit 0' >> script.sh
        
        
      - name: Line Count Check2
        run: |-
          wc -l ${{ env.NEW_BRANCH_REPORT_FILE }}
          wc -l ${{ env.MAIN_BRANCH_REPORT_FILE }}
          cat script.sh
          bash ./script.sh ${{ env.NEW_BRANCH_REPORT_FILE }}. ${{ env.MAIN_BRANCH_REPORT_FILE }}
        
