name: Flake8
on: [push, pull_request]

jobs:
  flake:    

    runs-on: ubuntu-latest
    steps:      

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          path: new_branch


      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: awslabs/aws-htc-grid
          path: main-branch
      
      - name: Install Flake8
        run: |-
          pip3 install flake8
      - run: ls -l -a
      - run: pwd
      
      - name: run flake8 on the new branch
        run: flake8 --config ./new_branch/.github/workflows/flake8.config --exit-zero ./new_branch

      - name: run flake8 on the new main
        run: flake8 --config ./new_branch/.github/workflows/flake8.config --exit-zero ./main-branch
